main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name="home"),
    path('about/', views.about, name="about"),
    path('advertisements/', views.advertisements, name="advertisements"),
    path('advertisement/<int:ad_id>/', views.advertisement_detail, name='advertisement_detail'),
    path('create_advertisement/', views.create_advertisement, name="create_ad"),
    path('contacts/', views.contacts, name="contacts"),
]

my_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path, reverse_lazy
from . import views
from django.contrib.auth import views as auth_views

app_name = 'users'

urlpatterns = [
    path('authentication/', views.authentication, name="authentication"),
    path('password-reset/', auth_views.PasswordResetView.as_view(
        template_name='users/password_reset_form.html',
        email_template_name='users/password_reset_email.html',
        success_url=reverse_lazy('users:password_reset_done')
    ), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='users/password_reset_done.html'
    ), name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html',
        success_url=reverse_lazy('users:password_reset_complete')
    ), name='password_reset_confirm'),
    path('password-reset/complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html',
    ), name='password_reset_complete'),
    path('registration/', views.registration, name="registration"),
    path('profile/', views.profile, name="profile"),
    path('logout/', views.logout_view, name="logout"),
]

main/models.py
from django.db import models
from users.models import User


class Advertisement(models.Model):
    CATEGORY_CHOICES = [
        ('sedan', 'Седан'),
        ('jeep', 'Позашляховик'),
        ('pickup', 'Пікап'),
        ('van', 'Фургон'),
        ('truck', 'Вантажівка'),
    ]

    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name="advertisements", verbose_name="Власник")
    car_name = models.CharField(max_length=255, verbose_name="Назва машини")
    category = models.CharField(max_length=20, choices=CATEGORY_CHOICES, verbose_name="Категорія")
    price = models.DecimalField(max_digits=10, decimal_places=0, verbose_name="Ціна")
    year_of_production = models.PositiveIntegerField(verbose_name="Рік випуску")
    mileage = models.PositiveIntegerField(verbose_name="Пробіг (км)")
    engine = models.CharField(max_length=100, verbose_name="Тип двигуна")
    location = models.CharField(max_length=255, verbose_name="Локація")
    owner_phone_number = models.CharField(max_length=15, verbose_name="Номер телефону власника")
    photo = models.ImageField(upload_to='car_photos/', verbose_name="Фото машини", null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата створення оголошення")

    def __str__(self):
        return f"{self.car_name} - {self.price}$ ({self.created_at})"

main/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import Advertisement
import re


class AdvertisementForm(forms.ModelForm):
    owner = forms.CharField(max_length=50, required=True)

    class Meta:
        model = Advertisement
        fields = ['car_name', 'category', 'price', 'year_of_production', 'mileage',
                  'engine', 'location', 'owner_phone_number', 'photo']
        widgets = {
            'category': forms.Select(choices=Advertisement.CATEGORY_CHOICES),
        }

    def clean_car_name(self):
        car_name = self.cleaned_data.get("car_name")
        if not any(char.isalpha() for char in car_name):
            raise ValidationError("Модель автомобіля повинна містити хоча б одну літеру.")
        return car_name

    def clean_year_of_production(self):
        year_of_production = self.cleaned_data.get("year_of_production")
        if year_of_production < 1990:
            raise ValidationError("Рік випуску автомобіля не може бути меншим за 1990.")
        if year_of_production > 2025:
            raise ValidationError("Рік випуску автомобіля не може бути більшим за 2025.")
        return year_of_production

    def clean_engine(self):
        engine = self.cleaned_data.get("engine")
        if not any(char.isdigit() for char in engine):
            raise ValidationError("Тип двигуна повинен містити хоча б одну цифру.")
        if not any(char.isalpha() for char in engine):
            raise ValidationError("Тип двигуна повинен містити хоча б одну літеру.")
        return engine

    def clean_location(self):
        location = self.cleaned_data.get("location")
        if not any(char.isalpha() for char in location):
            raise ValidationError("Локація розташування автомобіля повинна містити хоча б одну літеру.")
        return location

    def clean_owner(self):
        owner = self.cleaned_data.get("owner")
        if not any(char.isalpha() for char in owner):
            raise ValidationError("Ініціали продавця повинні містити хоча б одну літеру.")
        return owner

    def clean_owner_phone_number(self):
        owner_phone_number = self.cleaned_data.get("owner_phone_number")
        if not re.match(r'^\+?\d{10,15}$', owner_phone_number):
            raise ValidationError("Введіть номер телефон у форматі +380XXXXXXXXX.")
        return owner_phone_number

main/views.py
from django.shortcuts import render, redirect
from .utils import get_cached_currency_rate
from decimal import Decimal
from django.shortcuts import render, get_object_or_404
from django.db.models import F, FloatField
from django.db.models.functions import Round
from .models import Advertisement
from .forms import AdvertisementForm


def home(request):
    rate = round(get_cached_currency_rate("UAH"), 2)
    unique_users_count = Advertisement.objects.values("owner").distinct().count()
    if unique_users_count == 1 or unique_users_count % 10 == 1:
        users_text = f"{unique_users_count} користувач вже розмістив свої оголошення"
    elif unique_users_count in [2, 3, 4] and unique_users_count not in [12, 13, 14]:
        users_text = f"{unique_users_count} користувачі вже розмістили свої оголошення"
    else:
        users_text = f"{unique_users_count} користувачів вже розмістили свої оголошення"

    return render(request, 'main/index.html', {'rate': rate, 'users_text': users_text})


def about(request):
    rate = round(get_cached_currency_rate("UAH"), 2)
    return render(request, 'main/about.html', {'rate': rate})


def advertisements(request):
    rate = Decimal(str(round(get_cached_currency_rate("UAH"), 2)))
    min_price = request.GET.get('min_price')
    max_price = request.GET.get('max_price')
    category = request.GET.get('category')
    min_year = request.GET.get('min_year')
    max_year = request.GET.get('max_year')
    min_miles = request.GET.get('min_miles')
    max_miles = request.GET.get('max_miles')
    location = request.GET.get('location')

    advertisements = Advertisement.objects.annotate(
        price_uah=Round(F("price") * rate, 0)
    )

    if min_price:
        advertisements = advertisements.filter(price__gte=min_price)
    if max_price:
        advertisements = advertisements.filter(price__lte=max_price)
    if category:
        advertisements = advertisements.filter(category=category)
    if min_year:
        advertisements = advertisements.filter(year_of_production__gte=min_year)
    if max_year:
        advertisements = advertisements.filter(year_of_production__lte=max_year)
    if min_miles:
        advertisements = advertisements.filter(mileage__gte=min_miles)
    if max_miles:
        advertisements = advertisements.filter(mileage__lte=max_miles)
    if location:
        advertisements = advertisements.filter(location=location)

    count = advertisements.count()
    if count % 10 == 1 and count % 100 != 11:
        count_text = f"Знайдено {count} оголошення"
    elif count % 10 in [2, 3, 4] and count % 100 not in [12, 13, 14]:
        count_text = f"Знайдено {count} оголошення"
    else:
        count_text = f"Знайдено {count} оголошень"

    context = {
        'advertisements': advertisements,
        'rate': rate,
        'min_price': min_price,
        'max_price': max_price,
        'category': category,
        'min_year': min_year,
        'max_year': max_year,
        'min_miles': min_miles,
        'max_miles': max_miles,
        'location': location,
        'count_text': count_text
    }

    return render(request, 'main/advertisements.html', context)


def advertisement_detail(request, ad_id):
    ad = get_object_or_404(Advertisement, id=ad_id)
    rate = Decimal(str(round(get_cached_currency_rate("UAH"), 2)))
    ad.price_uah = round(ad.price * rate, 0)

    context = {
        'advertisement': ad,
        'rate': rate,
    }
    return render(request, 'main/advertisement_detail.html', context)


def create_advertisement(request):
    if request.method == 'POST':
        form = AdvertisementForm(request.POST, request.FILES)
        if form.is_valid():
            advertisement = form.save(commit=False)
            advertisement.owner = request.user  # Встановлюємо власника як поточного користувача
            advertisement.save()
            return redirect('main:home')
    else:
        form = AdvertisementForm()
    return render(request, 'main/create_advertisement.html', {'form': form})


def contacts(request):
    rate = round(get_cached_currency_rate("UAH"), 2)
    return render(request, 'main/contacts.html', {'rate': rate})

main/templates/main/about.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}Про нас{% endblock %}

{% block css %}<link rel="stylesheet" href="{% static 'main/css/about.css' %}">{% endblock %}

{% block content %}
<div class="blue"></div>
<div class="about-container">
    <h1 id="about">Трохи інформації про нас</h1>
    <div class="about-content">
        <section class="intro">
            <h2>Хто ми?</h2>
            <p>CarTrade – молода та амбітна компанія, заснована у 2025 році, що спеціалізується на продажу та купівлі автомобілів. Наша мета – створити зручну платформу, яка спрощує процес купівлі чи продажу авто.</p>
        </section>
        <section class="mission">
            <h2>Наша місія</h2>
            <p>Ми прагнемо стати провідною платформою на ринку, об'єднуючи продавців та покупців у зручному онлайн-середовищі. Кожного дня ми намагаємось стати кращими за наших конкурентів.</p>
        </section>
        <section class="mission">
            <h2>Наші цінності</h2>
            <p>Кінцевий користувач – основна цінність для нас. Ми продовжуємо працювати над впровадженням нових функцій та покращенням вже існуючих, щоб створити Ваш користувацький досвід ще кращим.</p>
        </section>
    </div>
</div>
<div class="blue"></div>
{% endblock %}

main/templates/main/advertisement_detail.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}{{ advertisement.car_name }}{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'main/css/advertisement_detail.css' %}">
{% endblock %}

{% block content %}
<div class="blue"></div>
<div class="about-container">
    <h1>{{ advertisement.car_name }}</h1>
</div>
<div class="ad-detail">
    <div class="image-container">
        {% if advertisement.photo %}
            <img id="ph" src="{{ advertisement.photo.url }}" alt="Фото {{ advertisement.car_name }}" width="615">
        {% endif %}
    </div>
    <div class="info-container">
        <p><strong>Ціна:</strong><span id="price"> {{ advertisement.price }} USD </span> <span id="bo">(≈ {{ advertisement.price_uah }} грн) </span></p>
        <p><strong>Рік випуску:</strong> {{ advertisement.year_of_production }} </p>
        <p><strong>Пробіг:</strong> {{ advertisement.mileage }} км</p>
        <p><strong>Двигун:</strong> {{ advertisement.engine }} </p>
        <p><strong>Локація:</strong> {{ advertisement.location }} </p>
        <p><strong>Дата створення:</strong> {{ advertisement.created_at }} </p>
        <a href="{% url 'main:advertisements' %}" class="btn">Повернутись до оголошень</a>
    </div>
    <div id="own">
        <p id="cont">Контакти продавця:</p>
        <div id="white">
            <p id="fir" class="r"><strong>Ім'я:</strong> {{ advertisement.owner }} </p>
            <p class="r"><strong>Номер телефону:</strong> {{ advertisement.owner_phone_number }} </p>
            <p class="r"><strong>Пошта:</strong> {{ advertisement.owner.email }} </p>
        </div>
    </div>
</div>
<div class="blue"></div>
{% endblock %}

main/templates/main/advertisements.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}Оголошення{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'main/css/advertisements.css' %}">
{% endblock %}

{% block content %}
<div class="blue"></div>
<div class="about-container">
    <div id="t" class="ic">
        <h1 id="ads">Наявні оголошення</h1>
        <div id="c">
            <p id="ccc"> {{ count_text }} </p>
        </div>
    </div>
</div>
<div class="ic">
<div class="ads-container">
    {% for ad in advertisements %}
        <div class="ad-card">
            <div class="ad-text">
                <h2> {{ ad.car_name }} </h2>
                <p id="first"><strong>Ціна:</strong><span> {{ ad.price }} USD </span> <span id="bl">(≈ {{ ad.price_uah }} грн) </span></p>
                <div class="data">
                    <div id="one">
                        <div class="ic">
                            <img id="yy" src="{% static 'main/images/calendar-days-solid.svg' %}" alt="рік"><p id="yy2"><strong>Рік випуску:</strong> {{ ad.year_of_production }} р.</p>
                        </div>
                        <div class="ic">
                            <img id="rr" src="{% static 'main/images/road-solid.svg' %}" alt="пробіг"><p id="rr2"><strong>Пробіг:</strong> {{ ad.mileage }} км.</p>
                        </div>
                    </div>
                    <div id="two">
                        <div class="ic">
                            <img id="ee" src="{% static 'main/images/gas-pump-solid.svg' %}" alt="двигун"><p id="ee2"><strong>Двигун:</strong> {{ ad.engine }}</p>
                        </div>
                        <div class="ic">
                            <img id="ll" src="{% static 'main/images/location-dot-solid.svg' %}" alt="локація"><p id="ll2"><strong>Локація:</strong> {{ ad.location }}</p>
                        </div>
                    </div>
                </div>
                <div class="ic">
                    <img id="tt" src="{% static 'main/images/clock-regular.svg' %}" alt="час"><p id="last"> {{ ad.created_at }} </p>
                </div>
            </div>
            <button class="id"><a href="{% url 'main:advertisement_detail' ad.id %}">Дізнатись більше</a></button>
            {% if ad.photo %}
                <div class="ad-photo">
                    <img id="car" src="{{ ad.photo.url }}" alt="Фото {{ ad.car_name }}" width="450">
                </div>
            {% endif %}
        </div>
    {% empty %}
        <p id="txt">Жодного оголошення не було знайдено.</p>
    {% endfor %}
</div>
    <div id="fil">
        <h3>Фільтри</h3>
        <form method="GET" action="{% url 'main:advertisements' %}">
            <p id="pr">Ціна (в USD):</p>
            <div class="ic">
                <p class="ot">Від</p>
                <input type="number" name="min_price" value="{{ min_price }}" min="0" step="1">
                <p class="ot">До</p>
                <input type="number" name="max_price" value="{{ max_price }}" min="0" step="1">
            </div>
            <div class="ic">
                <p id="catg">Категорія:</p>
                <select name="category" id="id_category">
                    <option value="" {% if not category %}selected{% endif %}>---------</option>
                    <option value="sedan" {% if category == "sedan" %}selected{% endif %}>Седан</option>
                    <option value="jeep" {% if category == "jeep" %}selected{% endif %}>Позашляховик</option>
                    <option value="pickup" {% if category == "pickup" %}selected{% endif %}>Пікап</option>
                    <option value="van" {% if category == "van" %}selected{% endif %}>Фургон</option>
                    <option value="truck" {% if category == "truck" %}selected{% endif %}>Вантажівка</option>
                </select>
            </div>
            <p id="year">Рік випуску:</p>
            <div class="ic">
                <p class="ot">Від</p>
                <input type="number" name="min_year" value="{{ min_year }}" min="1990" max="2025" step="1">
                <p class="ot">До</p>
                <input type="number" name="max_year" value="{{ max_year }}" min="1990" max="2025" step="1">
            </div>
            <p id="mile">Пробіг (в км):</p>
            <div class="ic">
                <p class="ot">Від</p>
                <input type="number" name="min_miles" value="{{ min_miles }}" min="0" step="1">
                <p class="ot">До</p>
                <input type="number" name="max_miles" value="{{ max_miles }}" min="0" step="1">
            </div>
            <p id="place">Розташування:</p>
            <div class="ic">
                <p class="ot">Місто</p>
                <input id="pp" type="text" name="location" value="{{ location|default:'' }}" placeholder="Введіть місто">
            </div>
            <button id="but" type="submit">Застосувати фільтри</button>
            <button id="but_2"><a href="{% url 'main:advertisements' %}">Скинути фільтри</a></button>
        </form>
    </div>
</div>
{% endblock %}

main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'main/css/index.css' %}">
    {% block css %}{% endblock %}
    <link rel="icon" type="image/png" href="{% static 'main/images/car-side-solid.svg' %}">
</head>
<body>
    <div class="main-container">
        <div class="menu-container">
            <ul class="menu">
                <li id="brand"><a href="{% url 'main:home' %}">CarTrade</a></li>
                <li class="icon {% if request.path == '/' %}active{% endif %}">
                    <a href="{% url 'main:home' %}"><img src="{% static 'main/images/house-solid.svg' %}" alt="головна">Головна</a>
                </li>
                <li class="icon {% if request.path == '/about/' %}active{% endif %}">
                    <a href="{% url 'main:about' %}"><img src="{% static 'main/images/shop-solid.svg' %}" alt="про нас">Про нас</a>
                </li>
                <li class="icon {% if request.path == '/advertisements/' %}active{% endif %}">
                    <a href="{% url 'main:advertisements' %}"><img src="{% static 'main/images/car-solid.svg' %}" alt="наявні авто">Наявні авто</a>
                </li>
                <li class="icon {% if request.path == '/contacts/' %}active{% endif %}">
                    <a href="{% url 'main:contacts' %}"><img src="{% static 'main/images/list-ul-solid.svg' %}" alt="контакти">Контакти</a>
                </li>
                <li class="icon {% if request.path == '/authentication/' %}active{% endif %}">
                    {% if user.is_authenticated %}
                    <a href="{% url 'main:home' %}"><img id="user" src="{% static 'users/images/user-solid.svg' %}" alt="користувач">{{ user.username }}</a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'users:profile' %}">Переглянути профіль</a></li>
                        <li><a href="{% url 'users:logout' %}">Вийти</a></li>
                    </ul>
                    {% else %}
                    <a href="{% url 'users:authentication' %}"><img src="{% static 'main/images/address-book-solid.svg' %}" alt="увійти">Увійти</a>
                    {% endif %}
                </li>
            </ul>
        </div>
        <div class="text-block">
            <p>Курс USD до UAH:</p>
            <div class="rate">
                <img id="dollar" src="{% static 'main/images/dollar-solid.svg' %}" alt="услуги"><p>{{ rate }} грн</p>
            </div>
        </div>
    </div>
    {% block content %}{% endblock %}
    <div class="footer">
        <p>© 2025 - CarTrade. Усі права захищено.</p>
    </div>
</body>
</html>

main/templates/main/contacts.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}Контакти{% endblock %}

{% block css %}<link rel="stylesheet" href="{% static 'main/css/contacts.css' %}">{% endblock %}

{% block content %}
<div class="blue"></div>
<div class="contacts-container">
    <h1 id="contacts">Наші контакти</h1>
    <div class="contacts-content">
        <section class="contact-info">
            <h2>Як з нами зв’язатися?</h2>
            <p><strong>Телефон:</strong> +1 (555) 123-4567</p>
            <p><strong>Email:</strong> support@cartrade.com</p>
            <p><strong>Адреса:</strong> 123 CarTrade Street, NY, USA</p>
        </section>
    </div>
</div>
<div class="map-container">
    <iframe
        src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3023.8578793166525!2d-74.00601588459402!3d40.71277597933011!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89c25a17f5e74a61%3A0x3c83a42a4033b5e6!2s123%20CarTrade%20Street%2C%20New%20York%2C%20NY%2C%20USA!5e0!3m2!1sen!2sus!4v1642512456679"
        width="92.5%"
        height="282"
        style="border:0;"
        allowfullscreen=""
        loading="lazy">
    </iframe>
</div>
<div class="blue"></div>
{% endblock %}

main/templates/main/create_advertisement.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Створення оголошення</title>
    <link rel="stylesheet" href="{% static 'main/css/create_advertisement.css' %}">
    <link rel="icon" type="image/png" href="{% static 'main/images/car-side-solid.svg' %}">
</head>
<body>
    <div class="auth-container">
        <a href="{% url 'main:home' %}">
            <img id="exit" src="{% static 'users/images/circle-xmark-solid.svg' %}" alt="вихід">
        </a>
        <div class="auth-box">
            <h1>Вас вітає <span class="blue">CarTrade</span>!</h1>
            <p>Будь ласка, заповніть форму</p>
            <form action="{% url 'main:create_ad' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                    <label for="{{ form.car_name.id_for_label }}">Модель автомобіля</label>
                    {{ form.car_name }}
                    {% if form.car_name.errors %}
                        <ul class="errorlist">
                            {% for error in form.car_name.errors %}
                                <li class="error-message">{{ error }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>
                <div class="form-group">
                    <label for="{{ form.category.id_for_label }}">Категорія автомобіля</label>
                    {{ form.category }}
                    {% if form.category.errors %}
                        <ul class="errorlist">
                            {% for error in form.category.errors %}
                                <li class="error-message">{{ error }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>
                <div class="form-group">
                    <label for="{{ form.price.id_for_label }}">Ціна автомобіля (в USD)</label>
                    {{ form.price }}
                    {% if form.price.errors %}
                        <ul class="errorlist">
                            {% for error in form.price.errors %}
                                <li class="error-message">{{ error }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>
                <div class="form-group">
                    <label for="{{ form.year_of_production.id_for_label }}">Рік випуску автомобіля</label>
                    {{ form.year_of_production }}
                    {% if form.year_of_production.errors %}
                        <ul class="errorlist">
                            {% for error in form.year_of_production.errors %}
                                <li class="error-message">{{ error }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>
                <div class="form-group">
                    <label for="{{ form.mileage.id_for_label }}">Пробіг (км)</label>
                    {{ form.mileage }}
                    {% if form.mileage.errors %}
                        <ul class="errorlist">
                            {% for error in form.mileage.errors %}
                                <li class="error-message">{{ error }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>
                <div class="form-group">
                    <label for="{{ form.engine.id_for_label }}">Тип двигуна</label>
                    {{ form.engine }}
                    {% if form.engine.errors %}
                        <ul class="errorlist">
                            {% for error in form.engine.errors %}
                                <li class="error-message">{{ error }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>
                <div class="form-group">
                    <label for="{{ form.location.id_for_label }}">Локація</label>
                    {{ form.location }}
                    {% if form.location.errors %}
                        <ul class="errorlist">
                            {% for error in form.location.errors %}
                                <li class="error-message">{{ error }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>
                <div class="form-group">
                    <label for="{{ form.owner.id_for_label }}">Ініціали продавця</label>
                    {{ form.owner }}
                    {% if form.owner.errors %}
                        <ul class="errorlist">
                            {% for error in form.owner.errors %}
                                <li class="error-message">{{ error }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>
                <div id="phone" class="form-group">
                    <label for="{{ form.owner_phone_number.id_for_label }}">Номер телефону продавця</label>
                    {{ form.owner_phone_number }}
                    {% if form.owner_phone_number.errors %}
                        <ul class="errorlist">
                            {% for error in form.owner_phone_number.errors %}
                                <li class="error-message">{{ error }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>
                <div id="file" class="form-group">
                    <label for="{{ form.photo.id_for_label }}">Фото автомобіля</label>
                    {{ form.photo }}
                    {% if form.photo.errors %}
                        <ul class="errorlist">
                            {% for error in form.photo.errors %}
                                <li class="error-message">{{ error }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>
                <div class="button-container">
                    <button type="submit" class="btn">Подати оголошення</button>
                </div>
            </form>
        </div>
    </div>
</body>
</html>

main/templates/main/index.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}Головна{% endblock %}

{% block content %}
<div class="blue"></div>
    <div class="text">
        <div class="buy">
            <p>Купуй чи продавай авто</p>
            <p>разом з нами.</p>
        </div>
        <div class="slang">
            <p> {{ users_text }} </p>
            <p>щодо продажу авто на нашому сайті.</p>
            <button class="view-requests"><a href="{% url 'main:advertisements' %}">Переглянути оголошення</a></button>
        </div>
    </div>
    <div class="blue"></div>
    <div class="question">
        <img id="run" src="{% static 'main/images/run_car.jpg' %}">
        <div id="phrase">
            {% if user.is_authenticated %}
            <p>Також хочеш подати оголошення, але все ще не зробив це?</p><br>
            <button><a href="{% url 'main:create_ad' %}">Подати оголошення</a></button>
            {% else %}
            <p>Хочеш подати своє оголошення, але досі не маєш особистого кабінету?</p><br>
            <button><a href="{% url 'users:registration' %}">Зареєструватися</a></button>
            {% endif %}
        </div>
        <img id="key" src="{% static 'main/images/key.jpg' %}">
    </div>
{% endblock %}